# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

addons:
    #chrome: stable
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation

cache:
  directories:
    - $HOME/.composer/cache

sudo: required
dist: trusty

matrix:
    include:
#        # Prestashop 1.7.1.x Branch       
#        - php: 5.6
#          env: PS_VERSION=1.7.1.x        
#        - php: 7.1
#          env: PS_VERSION=1.7.1.x        
#
#        # Prestashop 1.7.2.x Branch       
#        - php: 5.6
#          env: PS_VERSION=1.7.2.x        
#        - php: 7.1
#          env: PS_VERSION=1.7.2.x        
#
#        # Prestashop 1.7.3.x Branch       
#        - php: 5.6
#          env: PS_VERSION=1.7.3.x        
#        - php: 7.1
#          env: PS_VERSION=1.7.3.x        
#          
#        # Prestashop 1.7.4.x Branch       
#        - php: 5.6
#          env: PS_VERSION=1.7.4.x        
#        - php: 7.2
#          env: PS_VERSION=1.7.4.x        
#
#        # Prestashop 1.7.5.x Branch       
#        - php: 7.0
#          env: PS_VERSION=1.7.5.x        
        - php: 7.2
          env: PS_VERSION=1.7.5.x        

        # Prestashop develop Branch       
#        - php: 7.0
#          env: PS_VERSION=develop        
#        - php: 7.2
#          env: PS_VERSION=develop        
        
    allow_failures:
        - env: PS_VERSION=1.7.5.x
        - env: PS_VERSION=develop
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true
    
## Versions of PHP to test against
#php:
#    - "5.6"
#    - "7.0"
#    - "7.1"
##    - "7.2"

# Gloabl Env Configuration
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
#        
#    matrix:
#        - PS_VERSION=develop
#        - PS_VERSION=1.7.1.x
#        - PS_VERSION=1.7.2.x
#        - PS_VERSION=1.7.3.x
#        - PS_VERSION=1.7.4.x
#        - PS_VERSION=1.7.5.x
#        
#    allow_failures:
#        - php: 7.2       
#        
#    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
#    fast_finish: true        
    
before_script:

    - export MODULE_DIR=/tmp/SplashSync
    - export MODULE_SCRIPTS_DIR=/tmp/SplashSync/travis

    #   Move Module to Tmp Folder
    - bash travis/move_module.sh
    #   Install Prestashop
    - bash $MODULE_SCRIPTS_DIR/install_prestashop.sh
    #    Setup WebServer (Apache & PHP-Fpm)
    - bash $MODULE_SCRIPTS_DIR/install_webserver.sh
    #   Start Prestashop (Composer & More)
    - bash $MODULE_SCRIPTS_DIR/start_prestashop.sh
    #   Install Module
    - bash $MODULE_SCRIPTS_DIR/install_module.sh
    
script: 
    - cd $MODULE_DIR
    
    # Run Grump Main Test Sequence
    - php modules/splashsync/vendor/bin/grumphp run --testsuite=travis
    - cd $TRAVIS_BUILD_DIR

    # With PHP 7.2 => Execute CsFixer
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then php modules/splashsync/vendor/bin/grumphp run --testsuite=csfixer; fi    
    # With PHP 7.2 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.1" ]]; then php modules/splashsync/vendor/bin/grumphp run --testsuite=phpstan; fi 
    
    # Run PhpUnit Core Test Sequence (Will Enable the Module)
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist modules/splashsync/vendor/splash/phpcore/Tests/Core/
    
    # ALL PHP   =>  Run PhpUnit Local Sequence with No Data Inside
    - modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist --testsuite=Local
    
    # PHP7+     =>  Run PhpUnit Main Sequence
    - if [[ ${TRAVIS_PHP_VERSION:0:1} > "5" ]]; then phpdbg -qrr -d memory_limit=-1 modules/splashsync/vendor/bin/phpunit -c travis/phpunit.xml.dist; fi  
    # PHP5.6    =>  Without Php Debugger (Coverage x2 Faster)
    - if [[ ${TRAVIS_PHP_VERSION:0:1} < "7" ]]; then splash/vendor/bin/phpunit -c travis/phpunit.xml.dist; fi  
       
    # Show Outdated Packages  
    - cd $MODULE_DIR    
    - composer outdated
    
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_success:
    # Display Full List of Executed Tests    
    - cat coverage/executed.txt
    
after_failure:
