# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

addons:
    #chrome: stable
    apt:
        packages:
        - apache2
        - postfix
        - libapache2-mod-fastcgi
        - libappindicator1
        - fonts-liberation

cache:
  directories:
    - $HOME/.composer/cache

sudo: required
dist: trusty

# Versions of PHP to test against
php:
    - "5.6"
    - "7.0"
    - "7.1"
#    - "7.2"

# Gloabl Env Configuration
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=disabled
        
    matrix:
        - PS_VERSION=develop
        - PS_VERSION=master
        - PS_VERSION=1.7.1.x
        - PS_VERSION=1.7.2.x
        - PS_VERSION=1.7.3.x
        - PS_VERSION=1.7.4.x
        
    allow_failures:
        - env: PS_VERSION=develop
        
before_script:

    - export MODULE_DIR=/tmp/SplashSync
    - export MODULE_SCRIPTS_DIR=/tmp/SplashSync/build

#   Move Module to Tmp Folder
    - bash build/move_module.sh
#   Install Prestashop
    - bash $MODULE_SCRIPTS_DIR/install_prestashop.sh
#    Setup WebServer (Apache & PHP-Fpm)
    - bash $MODULE_SCRIPTS_DIR/install_webserver.sh
#   Start Prestashop (Composer & More)
    - bash $MODULE_SCRIPTS_DIR/start_prestashop.sh
#   Install Module
    - bash $MODULE_SCRIPTS_DIR/install_module.sh
    
script: 
    - cd $MODULE_DIR
    # Run Grump Main Test Sequence
    - php modules/splashsync/vendor/bin/grumphp run --testsuite=travis
    - cd $TRAVIS_BUILD_DIR
    # With PHP 7 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then php modules/splashsync/vendor/bin/grumphp run --testsuite=phpstan; fi 
#    # Run PhpUnit Core Test Sequence
    - phpunit -c phpunit.xml modules/splashsync/vendor/splash/phpcore/Tests/Core/
#    # Run PhpUnit Main Test Sequence
    - phpunit -c phpunit.xml
    - phpunit -c phpunit.xml
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:
