################################################################################
#
#  This file is part of SplashSync Project.
# 
#  Copyright (C) Splash Sync <www.splashsync.com>
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
# 
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################################
# Docker Compose File
#
# This Docker File intend to Create a Complete Dev Envirenement 
# for Splash Modules on Prestashop
#
# To us different PS Version coinfigured, you need to add hosts to /etc/hosts
# 
# 172.100.0.10        latest.prestashop.local
# 172.100.0.16        ps1-6.prestashop.local
# 172.100.0.17        ps1-7.prestashop.local
#
################################################################################


version: '2'

services:
    
    mysql:
        image: mysql:5.7
        container_name: prestashop_mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=admin"
            - "MYSQL_DATABASE=prestashop"
        networks:
            - prestashop
      
    prestashop:
        image: prestashop/prestashop
        container_name: prestashop_latest
        depends_on:
            - mysql
        volumes:
         - "./modules/splashsync:/var/www/html/modules/splashsync:ro"
         - "./docker/setup.sh:/var/www/html/modules/setup.sh:ro"
        environment:
            - DB_SERVER=mysql
            - DB_PREFIX=ps_latest_
            - PS_INSTALL_AUTO=1
            - PS_DOMAIN=latest.prestashop.local 
            - PS_FOLDER_ADMIN=_ad
            - PS_FOLDER_INSTALL=installed
            - ADMIN_MAIL=contact@splashsync.com
            - ADMIN_PASSWD=splashsync
            - SPLASH_WS_ID=69696969696
            - SPLASH_WS_KEY=ThisTokenIsNotSoSecretChangeIt
            - SPLASH_WS_HOST=dev.splashsync.local
        command: sh /var/www/html/modules/setup.sh
        networks:
            prestashop:
                ipv4_address: 172.100.0.10
                
    prestashop_1_7:
        image: prestashop/prestashop:1.7
        container_name: prestashop_1_7
        depends_on:
            - mysql
        volumes:
         - "./modules/splashsync:/var/www/html/modules/splashsync:ro"
         - "./docker/setup.sh:/var/www/html/modules/setup.sh:ro"
        environment:
            - DB_SERVER=mysql
            - DB_PREFIX=ps_1_7_
            - PS_INSTALL_AUTO=1
            - PS_DOMAIN=ps1-7.prestashop.local 
            - PS_FOLDER_ADMIN=_ad
            - PS_FOLDER_INSTALL=installed
            - ADMIN_MAIL=contact@splashsync.com
            - ADMIN_PASSWD=splashsync
            - SPLASH_WS_ID=69696969696
            - SPLASH_WS_KEY=ThisTokenIsNotSoSecretChangeIt
            - SPLASH_WS_HOST=dev.splashsync.local
        command: sh /var/www/html/modules/setup.sh
        networks:
            prestashop:
                ipv4_address: 172.100.0.17
        
    prestashop_1_6:
        image: prestashop/prestashop:1.6
        container_name: prestashop_1_6
        depends_on:
            - mysql
        volumes:
         - "./modules/splashsync:/var/www/html/modules/splashsync:ro"
         - "./docker/setup.sh:/var/www/html/modules/setup.sh:ro"
        environment:
            - DB_SERVER=mysql
            - DB_PREFIX=ps_1_6_
            - PS_INSTALL_AUTO=1
            - PS_DOMAIN=ps1-6.prestashop.local 
            - PS_FOLDER_ADMIN=_ad
            - PS_FOLDER_INSTALL=installed
            - ADMIN_MAIL=contact@splashsync.com
            - ADMIN_PASSWD=splashsync
            - SPLASH_WS_ID=69696969696
            - SPLASH_WS_KEY=ThisTokenIsNotSoSecretChangeIt
            - SPLASH_WS_HOST=dev.splashsync.local
        command: sh /var/www/html/modules/setup.sh
        networks:
            prestashop:
                ipv4_address: 172.100.0.16
                
networks:
    prestashop:
        driver: bridge
        ipam:
            config:
                - subnet: 172.100.0.0/24
                  gateway: 172.100.0.1
 